# Generated by Django 4.2.16 on 2024-12-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_adress',
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
    ]
