# Generated by Django 4.2.16 on 2024-12-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_add_age_field'),
        ('users_app', '0002_remove_user_email_adress_user_email_address'),
    ]

    operations = [
    ]
