# Generated by Django 5.1.3 on 2024-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
    ]
